steps:

  # ==================================================================================================
  #  1. Fetch Git LFS assets (pointers are in the source archive)
  # ==================================================================================================
  - name: 'gcr.io/cloud-builders/git'
    id: 'git-lfs-fetch'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update -qq
        apt-get install -y -qq git-lfs
        git lfs install --skip-repo
        git lfs fetch --all
        git lfs checkout
    dir: '/workspace'

  # ==================================================================================================
  #  2. Build the C# project
  # ==================================================================================================
  - name: 'witchpixels/godot4-omnibuilder3d:latest-4.5.1-mono'
    id: 'build-csharp'
    entrypoint: 'dotnet'
    args: ['build', 'Arena2006.csproj']
    dir: '/workspace'

  # ==================================================================================================
  #  5. Export Linux server and client
  # ==================================================================================================
  - name: 'witchpixels/godot4-omnibuilder3d:latest-4.5.1-mono'
    id: 'make-folders'
    args:
      - '-c'
      - |
        mkdir -p build/linux_server build/linux_client build/windows_client
    entrypoint: 'bash'
    dir: '/workspace'

  - name: "witchpixels/godot4-omnibuilder3d:latest-4.5.1-mono"
    id: "godot-import-check"
    entrypoint: godot
    args: ["-v", "--headless", "--path", ".", "--editor", "--quit"]
    dir: "/workspace"
    env:
      - HOME=/root
      - GODOT_USER_HOME=/workspace/.godot

  # ==================================================================================================
  #  3. Import the project into Godot to generate necessary files
  # ==================================================================================================
  - name: 'witchpixels/godot4-omnibuilder3d:latest-4.5.1-mono'
    id: 'godot-import'
    args:
      - '-c'
      - |
        godot --headless -e --import
        godot -v --headless --path . --editor --quit
    entrypoint: 'bash'
    dir: '/workspace'
    env:
      - HOME=/root
      - GODOT_USER_HOME=/workspace/.godot

  # ==================================================================================================
  #  4. Run integration tests
  # ==================================================================================================
  #- name: 'gcr.io/$PROJECT_ID/godot-builder:latest'
  #  id: 'run-tests'
  #  args:
  #    - '-c'
  #    - 'zsh tests/run_test.sh tests/test_client_car_spawn.sh && zsh tests/run_test.sh tests/test_client_car_respawn.sh'
  #  entrypoint: 'bash'
  #  dir: '/workspace'

  - name: 'witchpixels/godot4-omnibuilder3d:latest-4.5.1-mono'
    id: 'export-builds'
    args:
      - '-c'
      - |
        godot --headless --path . --export-release "Linux Server"
        godot --headless --path . --export-release "Linux Client"
        godot --headless --path . --export-release "Windows Client"
    entrypoint: 'bash'
    dir: '/workspace'
    env:
      - HOME=/root
      - GODOT_USER_HOME=/workspace/.godot


  # ==================================================================================================
  #  9. Upload the client build to a GCS bucket
  # ==================================================================================================
  - name: 'gcr.io/cloud-builders/gsutil'
    id: 'upload-client-build'
    args:
      - 'cp'
      - '-r'
      - 'build/linux_client/*'
      - 'build/windows_client/*'
      - 'gs://${_GCS_BUCKET_NAME}/$COMMIT_SHA/'
    dir: '/workspace'

  # ==================================================================================================
  #  6. Dockerize the server build and push to GCR
  # ==================================================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build-server'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/arena2006-server:$COMMIT_SHA'
      - '-f'
      - 'platform/Dockerfile.server'
      - 'build/linux_server'
    dir: '/workspace'
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push-server'
    args: ['push', 'gcr.io/$PROJECT_ID/arena2006-server:$COMMIT_SHA']

  # ==================================================================================================
  #  7. Substitute Project ID in Kubernetes manifests
  # ==================================================================================================
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'substitute-project-id'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s/YOUR_PROJECT_ID/$PROJECT_ID/g" platform/deployment.yaml
        sed -i "s|arena2006-server:latest|arena2006-server:$COMMIT_SHA|g" platform/deployment.yaml

  # ==================================================================================================
  #  8. Deploy the server to GKE
  # ==================================================================================================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    id: 'gke-deploy'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials "${_GKE_CLUSTER_NAME}" --region "${_GKE_CLUSTER_LOCATION}" --project "$PROJECT_ID" \
        || gcloud container clusters get-credentials "${_GKE_CLUSTER_NAME}" --zone "${_GKE_CLUSTER_LOCATION}" --project "$PROJECT_ID"
        kubectl apply -f platform/deployment.yaml -f platform/service.yaml --namespace=default

# ==================================================================================================
#  Artifacts Configuration
# ==================================================================================================
artifacts:
  objects:
    location: 'gs://${_GCS_BUCKET_NAME}/builds/$COMMIT_SHA/'
    paths: ['build/linux_client/*']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
